"""change address, user, order

Revision ID: 5f19460d9295
Revises: da96a29988d7
Create Date: 2024-02-13 23:03:43.740635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f19460d9295'
down_revision = 'da96a29988d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_id_json', mysql.JSON(), nullable=False))
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ban', sa.Integer(), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('confirm_password',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('email_verification',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verification',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('confirm_password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('is_ban')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('address_id')
        batch_op.drop_column('products_id_json')

    # ### end Alembic commands ###
