"""add relation ship betweenn order and address

Revision ID: 702964a3ddf9
Revises: 1bc77330ddaa
Create Date: 2024-02-22 17:58:29.767071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '702964a3ddf9'
down_revision = '1bc77330ddaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('address_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
