"""change product

Revision ID: d639a7f3549f
Revises: 5f19460d9295
Create Date: 2024-02-13 23:05:54.338974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd639a7f3549f'
down_revision = '5f19460d9295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
