"""first_migration

Revision ID: da96a29988d7
Revises: 
Create Date: 2024-02-13 22:57:23.366037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da96a29988d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=50), nullable=False))
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('street',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
