"""change set json to true in order

Revision ID: e781591f5fab
Revises: d639a7f3549f
Create Date: 2024-02-13 23:07:26.072237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e781591f5fab'
down_revision = 'd639a7f3549f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('products_id_json',
               existing_type=mysql.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('products_id_json',
               existing_type=mysql.JSON(),
               nullable=False)

    # ### end Alembic commands ###
